[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "../circuits/target" }]
optimizer = true
optimizer_runs = 1

[lint]
exclude_lints = [
    "mixed-case-variable",
    "screaming-snake-case-immutable",
    "unaliased-plain-import",
    "literal-instead-of-constant",
    "multi-contract-file",
    "too-many-digits",
    "internal-function-used-once",
    "modifier-used-only-once",
    "unused-error",
    "asm-keccak256",
    "inline-assembly",
    "low-level-calls",
    "pragma-inconsistent",
    "could-be-immutable",
    "unwrapped-modifier-logic",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
